### ISSUE TITLE
Program.readLine returns empty string on EOF with no characters read

### ISSUE THREAD

**Issue by wasamasa** [Corsaair/redtamarin#128]
I'm expecting that calling `Program.readLine` and hitting `C-d` will return `null`, however I get an empty string instead. This is kind of surprising, many languages follow this assumption (or alternatively, throw an error). For instance, `gets` in Ruby returns `nil` in that situation, `input` in Python throws an error.

I've worked around this with the following for now:

```actionscript
import C.stdio.*;
var input:String = fgets(0x7FFFFFFF, stdin);
if (input != null && input.charAt(input.length - 1) == '\n') {
    return input.slice(0, input.length - 1);
}
return input;
```

**Comment by zwetan** [comment]
"as is" in redtamarin 0.4.1
`Program.readLine()` is "dumb"

it is blocking, and then "exit" when it receives either `\n` (LF) or `EOF`

now <kbd>ctrl</kbd>+<kbd>d</kbd> is an interesting problem because
it does not send a signal

like those other
  - <kbd>ctrl</kbd>+<kbd>c</kbd> exit the program (SIGINT)
  - <kbd>ctrl</kbd>+<kbd>z</kbd> exit the program (SIGTSTP)
  - <kbd>ctrl</kbd>+<kbd>\\</kbd> exit the program (SIGQUIT)

so <kbd>ctrl</kbd>+<kbd>d</kbd> does not send a signal
but instead act as a kind of EOF which means
"flush the input I typed so far"

so to have more control over what is typed in the standard input
you could use `kbhit()` in `C.conio`

for example
```actionscript
import C.conio.*;
import C.errno.*;
import C.stdio.*;
import C.unistd.*;

import shell.*;

trace( "" );
trace( "blocking input: (type 'any phrase' followed by [ENTER] to quit)" );
var run:Boolean = true;
var i:int;
var char:int;
var key:String;
var buffer:String = "";

canonical(false);
echo(false);
while( run )
{
    i=kbhit();

    if( i != 0 )
    {
        char = getchar();

        // error
        if( char < 0 )
        {
            var e = new CError( "", errno );
            throw e;
        }

        // intercept ^D eg. EOT - End of Transmission
        if( char == 4 )
        {

            if( buffer == "" )
            {
                Program.write( "\n" );
            }
            else if( (buffer.length > 0) && (buffer.substr(buffer.length-1,1) != "\n") )
            {
                Program.write( "\n" );
            }
            
            trace( "\"" + buffer + "\"" );
            continue;
        }

        key  = String.fromCharCode( char );
        //trace( "key = " + key + "( char=" + char + ")" );
        
        // Note:
        // the ENTER key has different value
        // under POSIX it is LF "\n" 0x10
        // under WIN32 it is CR "\r" 0x13
        if( (key == "\n") || (key == "\r") )
        {
            run = false;
            Program.write( "\n" );
        }
        else if( key == "\n" )
        {
            continue;
        }
        else
        {
            //Program.write( "[" + key + "]" );
            
            // only write chars we can see for feedback
            if( (char >= 32) && (char <= 126) )
            {
                Program.write( key );
            }

            buffer += key;
        }

        i = 0;
    }
}
canonical(true);
echo(true);
trace( "You wrote \"" + buffer + "\"" );
```

now a harder problem would be to differentiate between
a <kbd>ctrl</kbd>+<kbd>c</kbd> that send SIGINT and
<kbd>ctrl</kbd>+<kbd>c</kbd> that is meant to send `End of Text / ^C / ETX`

which should be possible in the next version 0.4.2

**Comment by zwetan** [comment]
> I'm expecting that calling `Program.readLine` and hitting `C-d` will return `null`, however I get an empty string instead. This is kind of surprising, many languages follow this assumption (or alternatively, throw an error). For instance, `gets` in Ruby returns `nil` in that situation, `input` in Python throws an error.

now on this part I don't agree that `^D` should return `null`

following the logic that `^D` mean "End of Transmission"
it should tell `Program.readLine` to stop blocking
or stop waiting for the transmission

so something like that
```actionscript
var input:String = Program.readLine();
trace( input );
```

should have the following behaviour
  - wait for input (eg. block forever)
  - stop if either `\n` or `EOF` or `^D` is sent
  - return the accumulated buffer

in the case where nothing were written in the buffer
then yes it should return the empty string

again, as a default "dumb" behaviour

let me know what you think

**Comment by wasamasa** [comment]
Well, if `C-d` merely terminates recording characters to a buffer, then it's impossible to tell whether the user wants to quit (`EOF` sent with an empty buffer) or redirected input has terminated (`EOF` sent with non-empty buffer). Note how `fgets` signals the former case by returning `NULL` (and treats the latter case and regular termination with `\n` the same) which is why I can use it to construct a smarter `readLine`.

Imagine if someone wrote a REPL where they read user input with `Program.readLine`. That person would test what the function returns when the user indicates they want to quit with `C-d` on an empty line. As it's an empty string and empty strings are considered falsy, it wouldn't be unreasonable for that person to do something like `if (var input:String = Program.readLine()) {...}`, however they'd then run into the issue that if the user hits the Enter key on an empty line, the REPL would just quit! I've run into another programming language that used to have this very issue that was promptly declared a feature ("Quit the REPL instantly!"), but later removed (perhaps it made input redirection tricky because empty lines are common there). I also ran into another programming language that returned "q" in this case which is somewhat better.  Why not do the right thing and distinguish these cases properly?

**Comment by zwetan** [comment]
> Well, if `C-d` merely terminates recording characters to a buffer, then it's impossible to tell whether the user wants to quit (`EOF` sent with an empty buffer) or redirected input has terminated (`EOF` sent with non-empty buffer). Note how `fgets` signals the former case by returning `NULL` (and treats the latter case and regular termination with `\n` the same) which is why I can use it to construct a smarter `readLine`.

Which is why `Program.readLine` stay dumb
and if you need a smarter way you use another way

Redtamarin by default try to provide an API that works the same on all platforms
if you make a special case for `^D` under POSIX
then you gonna have to make a special case for `^Z` under WIN32

the `readline` functionality is just that: "read a line"
it imply that the input is text and not binary and that the line end with an `EOF`

this is the simplest thing that can work.

Now, if you need to do more advanced thing, the C API part of Redtamarin
allow to do those more advanced stuff, wether it is reading the stdin as binary,
or intercepting something like `^D`.

> Imagine if someone wrote a REPL where they read user input with `Program.readLine`. That person would test what the function returns when the user indicates they want to quit with `C-d` on an empty line. 

I would say that using `Program.readLine` for implementing a REPL is the wrong tool
I did implement few REPL and I always favoured using code similar to the one mentioned earlier using `kbhit()`

> As it's an empty string and empty strings are considered falsy, it wouldn't be unreasonable for that person to do something like `if (var input:String = Program.readLine()) {...}`, however they'd then run into the issue that if the user hits the Enter key on an empty line, the REPL would just quit!

It does not need to be like that.

There is a basic REPL in the Redtamarin shell
try something like `$ redshell_dd -repl`

internally in C++ it uses a `getUserInput()` method
```cpp
    char* PosixPartialPlatform::getUserInput(char* buffer, int bufferSize)
    {
        fflush(stdout);
        if (fgets(buffer, bufferSize, stdin) == NULL) {
            // EOF or error
            *buffer = 0;
            return NULL;
        }
        return buffer;
    }
```
this will not account for `^D`

you could implement the equivalent in AS3
```actionscript
import C.stdio.*;

function getUserInput( bufferSize:int ):String
{
    fflush( stdout );
    return fgets( bufferSize, stdin );
}
```

my point you would still have to handle `^D` in your REPL read line loop

now for catching the <kbd>enter</kbd> on an empty line
this is easily done wit the sample code using `kbhit()` I mentioned above

> Why not do the right thing and distinguish these cases properly?

there are all the tools in the C API to implement the "right thing" the way you see fit

in your case you want to distinguish between `^D` and `EOF` with the ENTER key
`Program.readLine()` doesn't do it the way you want then simply write your own readline function

others may want to read the input char by char
others may want to wrap the output in ANSI code to colorize it
others may want to read the whole line because they have to deal with UTF-8 input
others may want to use `echo()`/`canonical()` and replace typed input chars with `*` for password entry, etc.
others may need to be able to read the `stdin` as a binary stream and so not EOF on `^D` (eg. they do want the `0x04` byte)
others may need the input buffered in a particular way (`_IONBF`,`_IOLBF`,`_IOFBF`)

**Comment by wasamasa** [comment]
> this will not account for ^D

But it does! I can quit `redshell_dd` with `C-d` just fine because it returns `NULL` for that case. Hitting Enter prints the prompt again. Why not expose that function?

> my point you would still have to handle ^D in your REPL read line loop

Yes, by checking whether the return value is `null`. `Program.readLine` doesn't allow that. It always returns a string.

Anyway, the `kbhit()` solution is interesting, but overkill for my needs. A simple enhancement of `Program.readLine` is all I'm asking for.

**Comment by zwetan** [comment]
> > this will not account for ^D
> 
> But it does! I can quit `redshell_dd` with `C-d` just fine because it returns `NULL` for that case. Hitting Enter prints the prompt again. Why not expose that function?

please provide an example script where you describe expected behaviour
eg. it does that but I expect it to work like that

that you find `kbhit()` overkill, fine
but you can implement your own readline function in many different way
eg.
```actionscript
function readline( buffer:int ):String
{
    fflush( stdout );
    return fgets( buffer, stdin );
}
```

why it is so important that `Program.readLine` itself HAS TO change?

also bare in mind those few other things

[End-of-file](https://en.wikipedia.org/wiki/End-of-file)
> In UNIX the translation of the keystroke to EOF is performed by the terminal driver, so a program does not need to distinguish terminals from other input files. By default, the driver converts a Control-D character at the start of a line into an end-of-file indicator.

I proposed to take into account `^D` as an `EOF`, you seem not happy with that

also

> In Microsoft's DOS and Windows (and in CP/M and many DEC operating systems), reading from the terminal will never produce an EOF. Instead, programs recognize that the source is a terminal (or other "character device") and interpret a given reserved character or sequence as an end-of-file indicator; most commonly this is an ASCII Control-Z, code 26. Some MS-DOS programs, including parts of the Microsoft MS-DOS shell (COMMAND.COM) and operating-system utility programs (such as EDLIN), treat a Control-Z in a text file as marking the end of meaningful data, and/or append a Control-Z to the end when writing a text file.

When I say we keep  `Program.readLine` dumb it is also for cross-platform compatibility
eg. if you need more advanced usage in either POSIX or WIN32 build a better readline with the tools from the C API

also see [End-of-Transmission character](https://en.wikipedia.org/wiki/End-of-transmission_character)
> The EOT character in Unix is different from the Control-Z in DOS. The DOS Control-Z byte is actually sent and/or placed in files to indicate where the text ends. In contrast the Control-D causes the Unix terminal driver to signal the EOF condition, which is not a character, while the byte has no special meaning if actually read or written from a file or terminal.

`^Z` in WIN32 and `^D` in POSIX are not exactly the same
I would rather keep a simpler readline that works everywhere wit the same expected behaviour

I understand your use case but so far I'm not convinced

**Comment by wasamasa** [comment]
> please provide an example script where you describe expected behaviour
> eg. it does that but I expect it to work like that

```actionscript
import shell.Program;

function readline(prompt:String):String {
    Program.write(prompt);
    return Program.readLine();
}

function readWords(prompt:String):void {
    var word:String;
    do {
        word = readline(prompt);
        if (word == null) {
            trace('Null detected');
        } else if (word.length == 0) {
            trace('Empty string detected');
        } else {
            trace('Non-empty string detected');
        }
    } while (word != null);
}

readWords('> ');
```

This script is invoked with `printf "foo\n\nbar" | redshell test.as3`. I expect it to print "Non-empty string detected", "Empty string detected", "Non-empty string detected", "Null detected". It prints "Non-empty string detected", "Empty string detected", "Non-empty string detected", then does an infinite loop printing "Empty string detected".

> ^Z in WIN32 and ^D in POSIX are not exactly the same

Can't say anything about Windows support, but I'd expect that signalling `EOF` there should have the same results.

> why it is so important that Program.readLine itself HAS TO change?

My arguments for enhancing `Program.readLine`:

- It's a high-level function, yet offers worse behavior than the low-level function `fgets` for no apparent reason
- The enhancement allows telling apart no input (`C-d`) from empty input (Return)
- Why should someone have to construct a better `Program.readLine`, something that's taken for granted in pretty much every popular programming language?

**Comment by zwetan** [comment]
ok so after numerous tests her what happen

in **redtamarin v0.4.2(( most native methods have been replaced by AS3 implementations

in `Program` for example
you have `Program.useNativeTrace` which can be either `true` or `false`
and change the behaviour of the following functions

  - `trace()`
  - `tracef()`
  - `vtracef()`
  - `Program.write()`
  - `Program.writeLine()`
  - `Program.readLine()`

in the case of `Program.readLine()`
```actionscript
        public static function readLine():String
        {
            if( Program.useNativeTrace )
            {
                return Program._readLine();
            }
            else
            {
                return Program.standardInput.readLine( true );
            }
        }
```

the native method `Program._readLine()`
use the C++
```cpp
    Stringp ProgramClass::_readLine()
    {
        AvmCore* core = this->core();
        Stringp s = core->kEmptyString;
        wchar wc[64];
        int i=0;
        for( int c = getchar(); c != '\n' && c != EOF; c = getchar() )
        {
            wc[i++] = (wchar)c;
            if( i == 63 )
            {
                wc[i] = 0;
                s = s->append16(wc);
                i = 0;
            }
        }

        if( i > 0 )
        {
            wc[i] = 0;
            s = s->append16(wc);
        }

        return s;
    }
```

the `Program.standardInput.readLine( true );`
is an AS3 implementation more or less similar to the following
```actionscript
function input_readLine():String
{
    var CR:String = "\r";
    var LF:String = "\n";

    var line:String = "";
    var c:String;

    var run:Boolean = true;
    var b:int;
    var key:String;
    var kbuffer:ByteArray = new ByteArray();

    while( run )
    {
        b = fgetc( stdin );
        key = String.fromCharCode( b );

        if( b == EOF )
        {
            if( kbuffer.length == 0 )
            {
                return null;
            }

            kbuffer.position = 0;
            return kbuffer.readUTFBytes( kbuffer.length );
        }
        
        if( key == LF )
        {
            run = false;
        }
        else
        {
            kbuffer.writeByte( b );
        }
    }

    kbuffer.position = 0;
    line = kbuffer.readUTFBytes( kbuffer.length );
        
    if( line.charAt(line.length - 1) == CR )
    {
        line = line.substr( 0, line.length - 1);
    }

    return line;
}
```

the key part is instead of checking
```actionscript
if( (c == EOF) || (s == "\n") )
```

when `EOF` is encountered
```actionscript
if( c == EOF )
{
    if( buffer == "" )
    {
        return null; // ^D / ^Z caught
    }

   return buffer; // can be empty string
}
```
