### ISSUE TITLE
Loading external swf and executing a function with redtamarin

### ISSUE THREAD

**Issue by Swanty** [Corsaair/redtamarin#22]
Is it possible to load swf from file and then call a function that's inside the swf with redtamarin?

I see that there is shell.FileSystem for loading the file into bytearray, but there is no flash.display.Loader to load from bytearray

There is also the shell.Domain.load() and shell.Domain.loadBytes(), but as I understand it only supports .abc files?

**Comment by zwetan** [comment]
So "as is" no it's not possible

for now the default allow us only to load `.abc` files

but in a future update we will add a library/tool (name to be decided)
that will be able to dynamically load a SWF file and maybe SWC files
or at least dump the ABC from a SWF etc.

a SWF file format can be quite complicated, it can contains code in "doABC" tags,
but also assets like audio, image, video, font, etc.

I had already a go with a tool "swfinfo" to parse SWF files
see [SWFParser](https://code.google.com/p/maashaack/source/browse/tools/swfinfo/trunk/src/utils/SWFParser.as)

there are more advanced libraries like [as3swf](https://github.com/claus/as3swf)

and also abcdump/abcdis that you can find in the [src/utils](https://github.com/Corsaair/redtamarin/tree/master/src/utils)

and there are also a couple of thing missing in the native redtamarin libraries
for example: if you could load a SWF, then extract the ABC from the SWF and
load them in memory, it could break because you're missing some Flash or AIR native implementations, and that can be quite hard to debug.

For now, it is safer to compile your own ABC and load only ABC files

first, it will force you to use ASC to compile the AS3 source code
see [Compiling Programs](https://github.com/Corsaair/redtamarin/wiki/CompilingPrograms)
and be able to see upfront if there are compatibilities issues with redtamarin
and second, once you generate an ABC you can simply load it dynamically

Yes all that can become quickly very complicated, hence why a tool like [redbean](https://github.com/Corsaair/redtamarin/tree/master/src/tools/redbean) exists

I will document different use case, but let's be clear loading a SWF
produced for Flash or AIR is unlikely to be available soon

**Comment by Swanty** [comment]
Ah, that's unfortunate.
RedTamarin seems like the perfect project that I needed as in executing as3 from CLI

Specifically what I'm trying to do is execute a CrossBridge/FlasCC function that is inside an swf, since it's really hard to decompile/reverse engineer CrossBridge compiled actionscript back to its C/C++ equivalent, especially if the original code was obfuscated.

I tried using rabcdasm abcexport tool to get .abc from .swf, but upon loading it with Domain.load() function I get "VerifyError: Error #1014" which is what you said, that it will break since I'm missing some native implementations.

Either way, thank you!

**Comment by zwetan** [comment]
on this special case
"trying to do is execute a CrossBridge/FlasCC function that is inside an swf"
I can guarantee it will never work as redtamarin take a very different approach

if in CrossBridge project you were to use the `mkdir()` C function
this resolve to a syscall at compilation time which is then linked back
to a native call from the Flash/AIR API

in Redtamarin you can use the `mkdir()` C function
because it is a native library which call the "real" mkdir native C function

the two are not compatible at all
for now, adding CrossBridge support inside Redtamarin is not planed

so even if loading a SWF was possible,
loading a SWF produced by CrossBridge code would certainly break

**Comment by zwetan** [comment]
From Redtamarin 0.4.2 you will be able to dynamically load a SWF file 

A Person class
```as3
package test.as3examples
{

    // A basic class for testing
    public class Person
    {

        public var name:String;
        public var age:uint;

        public function Person( name:String = "", age:uint = 0 )
        {
            this.name = name;
            this.age = age;
        }

        public function toString():String
        {
            return "{Person \"" + name + "\" age: " + age + "}";
        }

    }

}
```
you compile it to `Person.swf`
eg. `$ java -jar asc.jar -AS3 -optimize -d -import redtamarin.abc -swf Person,100,100 Person.as`

now at runtime you can load it with either
`Runtime.load( filename:String ):Boolean`
or `Runtime.loadAnyBytes( b:ByteArray, filename:String ):int`

example
```as3
import shell.*;

var loaded:Boolean = Runtime.load( "Person.swf" );
trace( "Person class dynamically loaded: " + loaded );

// now that the definition is in-memory
// you can directly use any package, class, interface, etc.
// as if it was part of your code
import test.as3examples.Person;

// there is a limitation, you can not type the var with Person
// eg. 'var johndoe:Person' will fail as Person need to be a constant
var johndoe:* = new Person( "John Doe", 21 );
trace( "johndoe = " + johndoe );
trace( "is Person class: " + (johndoe is Person) );
```

Only SWF containing AS3 definitions in doABC tags are supported

what will not work or be supported

  - SWF compiled with `playerglobal.swc` or `airglobal.swc`   
    that use native implementations not available in Redtamarin
  - SWF compiled with CrossBridge/FlasCC
     that depends on C/C++ libraries

`Runtime.load()` can dynamically load either `*.as`, `*.abc` or `*.swf` files
but it is not "magic", those files need to define AS3 code that can actually run inside Redtamarin

**Comment by zwetan** [comment]
so to this

> Specifically what I'm trying to do is execute a CrossBridge/FlasCC function that is inside an swf, since it's really hard to decompile/reverse engineer CrossBridge compiled actionscript back to its C/C++ equivalent, especially if the original code was obfuscated.

I orignally answered

> on this special case
"trying to do is execute a CrossBridge/FlasCC function that is inside an swf"
I can guarantee it will never work as redtamarin take a very different approach
> 
> if in CrossBridge project you were to use the `mkdir()` C function
this resolve to a syscall at compilation time which is then linked back
to a native call from the Flash/AIR API
> 
> in Redtamarin you can use the `mkdir()` C function
because it is a native library which call the "real" mkdir native C function
> 
> the two are not compatible at all
for now, adding CrossBridge support inside Redtamarin is not planed
> 
> so even if loading a SWF was possible,
loading a SWF produced by CrossBridge code would certainly break

And I was wrong :)

For something unrelated, I went a lot more in deep into the [crossbridge](http://crossbridge.io/) sources, and even if **crossbridge** and **redtamarin** have a completely different approach, there are not necessarily incompatible.

It not gonna happen overnight, but supporting crossbridge is definitively possible
but there will be some limitations

  - probably do a crossbridge compile with a path
    (eg. already generated crossbridge libraries would probably have to be recompiled)
  - no UI or other GUI rendering
  - no support for Flash API not implemented in Redtamarin yet
  - maybe not a full support of pthreads

That said, it should be possible to use crossbridge to compile C/C++ sources to `.abc` and/or `.swf` and/or `.swc` and use that library in a redtamarin project.

So, as part of the different "glue" libraries, crossbridge support is back on the map as "planed".

Don't hold your breath though, it could take a while (~1 year) for this to work with redtamarin.

**Comment by zwetan** [comment]
see #129 adding CrossBridge support
